# DT binding for the Combo-Lead module.

title: ZMK Combos (Combo-Lead)

description: Adds leader-combo specific properties to the stock ZMK combo binding

compatible: "zmk,combos"
extend: true

child-binding:
  description: "A combo with optional leader extra positions"

  properties:
    bindings:
      type: phandle-array
      required: true
    key-positions:
      type: array
      required: true
    key-positions-leader:
      type: array
      required: false
    timeout-ms:
      type: int
      default: 50
    require-prior-idle-ms:
      type: int
      default: -1
    key-positions-first-exclude:
      type: array
      required: false
    slow-release:
      type: boolean
    layers:
      type: array 